### ISSUE TITLE
database관련 공지

### ISSUE THREAD

**Issue by dianakoh** [dianakoh/management#6]
aws 사용에서 요금문제가 발생하여
local 서버를 이용하는 것으로 방법을 변경하려고 함

local에서 mysql을 사용하는 방법은
http://withcoding.com/m/26
사이트를 참고

**Comment by hahahahyein** [comment]
맞아요... 요금 문제를 해결하고 일단 개인 pc에서 local서버를 각자 테스팅해보는 것이 좋을 것 같습니다.

좋은 자료 공유 감사합니다!!
